### ISSUE TITLE
will it work on pi4?

### ISSUE THREAD

**Issue by AndreV84** [Chatter-Software-Development/ChatterSync#2]
is pi4 implementation tested/ known to be working?

**Comment by peteoxenham** [comment]
Haven't tested it. It must be used via the USB-C port since that supports "OTG" as they call it. You'll need a USB-C to USB-A Male cable, and be sure that whatever system you're plugged into can supply enough power.
If you test it, let me know how it goes!

**Comment by peteoxenham** [comment]
Confirmed compatible on the Pi 4 by `Wotano[28]` on Discord!

**Comment by AndreV84** [comment]
can we confirm that they used the the chatter OS image to pi4?
or pi4 with default OS from raspberry?
Thanks
AV
