### ISSUE TITLE
zero 2 w compatability

### ISSUE THREAD

**Issue by milo-72** [Chatter-Software-Development/ChatterSync#4]
I tried using a zero 2 w,  raspberry states the 2 is backwards compatible with the zero. I'm assuming that it doesn't work with the software as I cant get it to boot with the chattersync software installed, has anyone else used a zero 2 with chattersync ?

**Comment by peteoxenham** [comment]
I see you closed the issue, did you find anything out? I haven't had a chance to check on this yet.

P

**Comment by milo-72** [comment]
Hi Pete, 
yes, I found that it works well with the zero 2. 
I'm not familiar with git hub or how the pi worked.
I had made a mistake when loading the files.
I loaded the files in git hub and not the linked file in the image folder.
What through me a curve ball was that the image loader did not give an error so I assumed I had transferred the operating system correctly.
Once I used the correct image it went well.
Thank you for releasing this and all your efforts with this, its a great tool you've created.
